packaging_format = 2

id = "ums"
name = "Universal Media Server"
description.en = "A DLNA, UPnP and HTTP(S) Media Server"
description.fr = "Un Serveur Multimedia DLNA, UPnP et HTTP(S)"

version = "14.8.0~ynh1"

maintainers = ["Krakinou"]

[upstream]
license = "GPL-2.0-or-later"
website = "www.universalmediaserver.com"
admindoc = "https://github.com/UniversalMediaServer/UniversalMediaServer/wiki"
code = "https://github.com/UniversalMediaServer/UniversalMediaServer"

[integration]
yunohost = ">= 11.1.18"
architectures = "all"
multi_instance = false
ldap = false
sso = false
disk = "1G"
ram.build = "350M"
ram.runtime = "350M"

[install]
    [install.domain]
    help.en = "UMS require its own subdomain"
    help.fr = "UMS a besoin de son propre sous-domaine"
    type = "domain"

    [install.init_main_permission]
    help.en = "Everybody will be able to access your media on the internet without connecting to Yunohost"
    help.fr = "Tout le monde pourra voir vos media sans se connecter à Yunohost"
    type = "group"
    default = "visitors"

    [install.server_name]
    ask.en = "By which name should UMS be identified by your renderer"
    ask.fr = "Par quel nom UMS doit-il être identifié par vos appareils"
    help.en = "This has no impact on the way the server will work and is only use to identify it on the network"
    help.fr = "Ceci n a aucun impact sur le fonctionnement du serveur et sert uniquement à l identifier sur le réseau"
    type = "string"
    example = "MyUMS"
    default = "UniversalMediaServer"

    [install.interface]
    ask.en = "Which network interface do you want to use?"
    ask.fr = "Quel réseau souhaitez vous utiliser?"
    help.en = "On lan, the interface is usually eth0, on wifi it s usually wlan0"
    help.fr = "En filaire, l interface est souvent eth0, en wifi wlan0"
    type = "string"
    default = "eth0"

[resources]
        [resources.sources.main]
        arm64.url = "https://github.com/UniversalMediaServer/UniversalMediaServer/releases/download/14.8.0/UMS-14.8.0-arm64.tgz"
        arm64.sha256 = "f25ac384f9c66cacf25e1a6c9fe49f81ffab781e3993b0f04626fcebd41889f7"
        amd64.url = "https://github.com/UniversalMediaServer/UniversalMediaServer/releases/download/14.8.0/UMS-14.8.0-x86_64.tgz"
        amd64.sha256 = "db25a58d2ab6ff9d9b86c4b8186a018231e5f677c61e82b2f7e183297bd76637"
        armhf.url = "https://github.com/UniversalMediaServer/UniversalMediaServer/releases/download/14.8.0/UMS-14.8.0-armhf.tgz"
        armhf.sha256 = "3dc2b953ec47a20bfd7e624c81ffcad367f6739533cdf75b1d765a6ac572efbb"
        i386.url = "https://github.com/UniversalMediaServer/UniversalMediaServer/releases/download/14.8.0/UMS-14.8.0-x86.tgz"
        i386.sha256 = "8007a191f5eb51d5067de733b7a36082534ab88aca9b4d8f33a934886ddce6d1"

        autoupdate.strategy = "latest_github_release"

        autoupdate.asset.arm64 = ".*-arm64.tgz"
        autoupdate.asset.amd64 = ".*-x86_64.tgz"
        autoupdate.asset.armhf = ".*-armhf.tgz"
        autoupdate.asset.i386 = ".*-x86.tgz"

    [resources.ports]
    main.default = 9001
    rend.default = 5001
    rend.exposed = "TCP"

    [resources.system_user]
    #UMS require a home path for the user as config files are stored in there
    home = '/home/yunohost.app/__APP__'

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"
    main.auth_header=false

    [resources.apt]
    packages = "mediainfo dcraw mencoder mplayer vlc"
    packages_from_raw_bash = """
        if [[ "$YNH_ARCH" == "armhf" ]] || [[ "$YNH_ARCH" == "arm64" ]]; then
           echo openjdk-17-jre
        fi
    """
